### ISSUE TITLE
Output text on Windows

### ISSUE THREAD

**Issue by parasiteoflife** [n7olkachev/imgdiff#11]
I've compared two images to test this and I got this output

```
←[1;31mFailure!←[0m Images are different.
Different pixels: ←[1;31m670866←[0m
```

Is this supposed to look like this?

**Comment by n7olkachev** [comment]
No it's not, what terminal emulator do you use?

**Comment by parasiteoflife** [comment]
I found out those characters are ANSI color codes. I'm using CMD on Windows.

**Comment by n7olkachev** [comment]
Yep, as I understand you can enable support for this https://superuser.com/questions/413073/windows-console-with-ansi-colors-handling
If you want to parse it, you can still do this just skipping those codes as they're static

**Comment by parasiteoflife** [comment]
Yes, enabling that worked. thanks.
