### ISSUE TITLE
Provide the MacOS-x86 build

### ISSUE THREAD

**Issue by dmtrKovalenko** [n7olkachev/imgdiff#4]
ODiff creator is here :D

**Comment by n7olkachev** [comment]
I've added darwin-386 binary to the latest published release, but can't test it.

**Comment by dmtrKovalenko** [comment]
By the way where did you run the comparison?

**Comment by n7olkachev** [comment]
On my local machine. Linux, Intel(R) Core(TM) i7-4700HQ CPU @ 2.40GHz, 8 cores.
