### ISSUE TITLE
Make the module available for developers

### ISSUE THREAD

**Issue by Mik-** [n7olkachev/imgdiff#6]
To integrate your tool in an other projects, the module path must be changed from `imgdiff` to `github.com/n7olkachev/imgdiff`.

So one can use your project as package. It would be great, e.g. in unit tests.

**Comment by utkarshpaliwal9** [comment]
+1 from my side. Please update asap.

**Comment by n7olkachev** [comment]
@Mik- is it ok now?

**Comment by Mik-** [comment]
It looks good to me, but I can't fully test it, as a new tag (v1.0.1) is missing.

**Comment by n7olkachev** [comment]
Tagged

**Comment by Mik-** [comment]
Works great now. Thanks.
