### ISSUE TITLE
Output is a zero-byte PNG file

### ISSUE THREAD

**Issue by eliseumds** [n7olkachev/imgdiff#8]
Version: 1.0.0

It computed the number of different pixels, but the output is empty.

Example:

```sh
curl -O https://user-images.githubusercontent.com/640840/112396875-03837d80-8ccf-11eb-8aa2-ef605eb6ab60.png
curl -O https://user-images.githubusercontent.com/640840/112396905-0da57c00-8ccf-11eb-8cd3-dab6d42cbfa1.png

./bin/imgdiff-darwin-amd64 --threshold 0.01 112396875-03837d80-8ccf-11eb-8aa2-ef605eb6ab60.png 112396905-0da57c00-8ccf-11eb-8cd3-dab6d42cbfa1.png output_diff.png
```

I get this output:

```
Failure! Images are different.
Different pixels: 3992
```

But the file is empty:

```
0B 24 Mar 18:34 output_diff.png
```

Any ideas? This is a fantastic tool that really boosted our end-to-end screenshots tests. I get these zero-byte files every ~1-2 in 100 diffs.

**Comment by n7olkachev** [comment]
I've published a fix in v1.0.2, could you verify?

**Comment by eliseumds** [comment]
@n7olkachev I can't run the binary. First I get `permission denied` (it didn't happen with the v1.0.0 binary), then I try to run it with sudo and get `./imgdiff-darwin-amd64: command not found`.

**Comment by n7olkachev** [comment]
Try `chmod +x imgdiff-darwin-amd64`

**Comment by eliseumds** [comment]
@n7olkachev omg, obviously, I need my morning coffee xD

It works now!
